version: "3.7"

services:
  millenniumevent_api:
    container_name: millenniumevent_api
    hostname: millenniumevent_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

    networks:
      default_network:
        ipv4_address: 172.0.0.21
    
    environment:
        - APPSETTINGS="Data/appsettings.json"
        - CORS_ORIGIN="https://localhost/"

networks:
  default_network:
    external: true